
############################## navigation ###############################

# main menu
[[main]]
name = "Portada"
URL = "/"
weight = 1

# [[main]]
# name = "Acerca de"
# URL = "about/"
# weight = 2

[[main]]
name = "Blog"
URL = "blog/"
weight = 3

[[main]]
name = "Contacto"
URL = "contact/"
weight = 4

# [[main]]
# name = "Sample Page"
# URL = "sample-page/"
# weight = 5

# only desktop menu
# [[desktop]]
# name = "Contacto"
# URL = "contact/"
# weight = 1

